# Generated by Django 5.2.1 on 2025-06-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statue_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statue',
            name='image',
            field=models.ImageField(upload_to='statue/'),
        ),
    ]
