# Generated by Django 5.2.1 on 2025-06-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statue_app', '0002_alter_statue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statue',
            name='image',
            field=models.ImageField(upload_to='statues/'),
        ),
    ]
