# Generated by Django 5.2.1 on 2025-06-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statue_app', '0003_alter_statue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='statue/')),
            ],
        ),
    ]
